services:
  postgres:
    image: postgres:16-alpine
    container_name: extension-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bridge_extension_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "1234:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
  backend:
    build: .
    container_name: build-extension-api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: bridge_extension_db
      ATTIO_CLIENT_ID: ${ATTIO_CLIENT_ID}
      ATTIO_CLIENT_SECRET: ${ATTIO_CLIENT_SECRET}
      ATTIO_REDIRECT_URI: ${ATTIO_REDIRECT_URI}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - postgres

volumes:
  pgdata:
  pgadmin: